// AUTO-GENERATED by scripts/generate-projects-registry.mjs — do not edit by hand.
// Run `npm run generate:projects` after adding or removing a project in ./data.
import type { Project } from './types';
import project0 from './data/victorian-roof-replacement-martinsburg-wv';

/** Every authored project (published or draft). Order here does not matter. */
export const PROJECT_MODULES: Project[] = [
  project0,
];
