// AUTO-GENERATED by scripts/generate-projects-registry.mjs — do not edit by hand.
// Run `npm run generate:projects` after adding or removing a project in ./data.
import type { Project } from './types';
import project0 from './data/composite-deck-build-martinsburg';
import project1 from './data/new-construction-framing-to-finish';
import project2 from './data/signature-kitchen-remodel-eastern-panhandle';
import project3 from './data/stone-facade-exterior-upgrade';
import project4 from './data/victorian-roof-replacement-martinsburg-wv';
import project5 from './data/walk-in-shower-bathroom-remodel';

/** Every authored project (published or draft). Order here does not matter. */
export const PROJECT_MODULES: Project[] = [
  project0,
  project1,
  project2,
  project3,
  project4,
  project5,
];
