const fs=require('fs'); const path=require('path'); const sharp=require('sharp'); const crypto=require('crypto');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const sources=[...walk('src'),...walk('content')].filter(p=>/\.(tsx?|mdx?|json|css)$/.test(p)).map(p=>({p,s:fs.readFileSync(p,'utf8')}));
const files=walk('public/images').filter(p=>/\.(jpe?g|png|webp|avif)$/i.test(p)).sort();
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');
(async()=>{const items=[];for(const [i,p]of files.entries()){const m=await sharp(p).metadata(); const url=p.slice(6);const refs=sources.filter(x=>x.s.includes(url)).map(x=>x.p);items.push({id:i+1,path:p,url,width:m.width,height:m.height,bytes:fs.statSync(p).size,hash:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),refs});}
fs.writeFileSync('.vercel/image-review/inventory.json',JSON.stringify(items,null,2));
for(let start=0;start<items.length;start+=16){const group=items.slice(start,start+16), layers=[];for(const [j,v]of group.entries()){const left=j%4*300,top=Math.floor(j/4)*235;layers.push({input:await sharp(v.path).rotate().resize(284,180,{fit:'inside'}).extend({top:0,bottom:0,left:0,right:0}).toBuffer(),left:left+8,top:top+5});const name=v.path.replace('public/images/','');const lines=[`${v.id}. ${name.slice(0,36)}`,name.slice(36),`${v.width}x${v.height} | ${Math.round(v.bytes/1024)}KB | ${v.refs.length} source refs`];const label=`<svg width="300" height="50"><style>text{font:12px sans-serif;fill:#fff}</style>${lines.map((s,k)=>`<text x="8" y="${13+k*15}">${esc(s)}</text>`).join('')}</svg>`;layers.push({input:Buffer.from(label),left,top:top+183});}await sharp({create:{width:1200,height:Math.ceil(group.length/4)*235,channels:3,background:'#192436'}}).composite(layers).jpeg({quality:88}).toFile(`.vercel/image-review/sheet-${start/16+1}.jpg`);}
console.log(JSON.stringify({total:items.length,referenced:items.filter(i=>i.refs.length).length,unreferenced:items.filter(i=>!i.refs.length).map(i=>i.path),small:items.filter(i=>i.width<800).map(i=>({id:i.id,path:i.path,width:i.width,refs:i.refs.length}))}));})();
